-- Datos de ejemplo (máx. 5 registros por tabla) para poder probar los catálogos
-- de "Ingresa a" sin tener que darlos de alta manualmente uno por uno.

INSERT INTO area (nombre_area) VALUES
    ('Salud'),
    ('Exactas'),
    ('Humanidades'),
    ('Administrativas');

INSERT INTO universidad (nombre_universidad) VALUES
    ('UV'),
    ('BUAP'),
    ('NAVAL'),
    ('TECNM ORIZABA'),
    ('TECNM VERACRUZ'),
    ('UPN'),
    ('UPV'),
    ('NORMAL TLACOTALPAN'),
    ('NORMAL PUEBLA'),
    ('BENV'),
    ('UTCV'),
    ('UPH'),
    ('UNPA'),
    ('IPN'),
    ('MILITAR'),
    ('UNAM'),
    ('CHAPINGO'),
    ('UANL'),
    ('UAM'),
    ('UABJO'),
    ('ENSEP'),
    ('UDG');

INSERT INTO carrera (nombre_carrera, id_area) VALUES
    ('Medicina', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Odontología', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Enfermería', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Psicología', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Nutrición', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Veterinaria', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Fisioterapia', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Terapia Física', (SELECT id_area FROM area WHERE nombre_area = 'Salud')),
    ('Ing Matemáticas', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Física', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Química', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Biología', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Arquitectura', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Civil', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Mecánica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Eléctrica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Sistemas', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Electrónica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Mecatrónica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Actuaría', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Diseño Gráfico', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('QFB', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Agronomía', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing en Alimentos', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ciencias Puras', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ingenierías Clásicas', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ingeniería Computacional', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Aeronáutica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Biotecnología', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Industrial', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Energías Renovables', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Mantenimiento Industrial', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Tecnologías de la Información', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Nanotecnología', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Agroindustrial', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Biotecnológica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Agrónoma', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Aeronaval', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing en Sistemas Navales', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Hidrografía', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Constructor', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Comunicaciones y Electrónica', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Ing Computación', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Piloto Aviador', (SELECT id_area FROM area WHERE nombre_area = 'Exactas')),
    ('Derecho', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Filosofía', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Historia', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Artes', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Criminología', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Comunicación', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Ciencias Sociales', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Sociología', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Pedagogía', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Psicología Educativa', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Educación Indígena', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Educación Básica', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Educación Especial', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Educación Física', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Educación Secundaria', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Sociología Rural', (SELECT id_area FROM area WHERE nombre_area = 'Humanidades')),
    ('Administración', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Contaduría', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Economía', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Mercadotecnia', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Negocios Internacionales', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Turismo', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Administración Industrial', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Relaciones Comerciales', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Gestión Empresarial', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Desarrollo de Negocios', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Gastronomía', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Gestión de Proyectos', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas')),
    ('Logística Naval', (SELECT id_area FROM area WHERE nombre_area = 'Administrativas'));

INSERT INTO carrera_universidad (id_carrera, id_universidad) VALUES
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Fisioterapia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Fisioterapia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Fisioterapia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Veterinaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Nutrición'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NAVAL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NAVAL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Medicina'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Odontología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Enfermería'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNPA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Terapia Física'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPH')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Matemáticas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Física'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Biología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Civil'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Eléctrica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Matemáticas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Física'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Biología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Civil'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecatrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Actuaría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Diseño Gráfico'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Matemáticas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'QFB'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Biología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Civil'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecatrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Actuaría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Matemáticas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'QFB'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Biología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Civil'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecatrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Agronomía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'QFB'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing en Alimentos'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Biología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Civil'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecatrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ciencias Puras'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ingenierías Clásicas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ingeniería Computacional'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Arquitectura'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ciencias Puras'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Aeronáutica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecatrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Biotecnología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Eléctrica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Industrial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecánica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Eléctrica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Industrial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Química'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Sistemas'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Energías Renovables'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mantenimiento Industrial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Mecatrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Tecnologías de la Información'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Nanotecnología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Agroindustrial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPH')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Biotecnológica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPH')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Agrónoma'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'CHAPINGO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Aeronaval'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NAVAL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing en Sistemas Navales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NAVAL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Hidrografía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NAVAL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Constructor'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Comunicaciones y Electrónica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Computación'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Piloto Aviador'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'MILITAR')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing en Alimentos'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNPA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ing Biotecnológica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNPA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Filosofía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Historia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Artes'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Criminología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Filosofía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Comunicación'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Artes'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Criminología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Filosofía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ciencias Sociales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Comunicación'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Artes'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Filosofía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ciencias Sociales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Comunicación'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Artes'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Filosofía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ciencias Sociales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Comunicación'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Artes'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Filosofía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Ciencias Sociales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Comunicación'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Derecho'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Sociología'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Artes'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Pedagogía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Psicología Educativa'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Indígena'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Pedagogía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Básica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Básica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NORMAL TLACOTALPAN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Básica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NORMAL PUEBLA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Especial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NORMAL PUEBLA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Básica'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BENV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Física'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BENV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Especial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BENV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Educación Secundaria'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'ENSEP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Sociología Rural'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'CHAPINGO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Mercadotecnia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Negocios Internacionales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Mercadotecnia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Negocios Internacionales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'BUAP')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Mercadotecnia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Negocios Internacionales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UANL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Mercadotecnia'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Turismo'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UDG')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Negocios Internacionales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Turismo'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UAM')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UABJO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Contaduría'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración Industrial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Relaciones Comerciales'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Turismo'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'IPN')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Gestión Empresarial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM ORIZABA')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Gestión Empresarial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'TECNM VERACRUZ')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Desarrollo de Negocios'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Gastronomía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Gestión de Proyectos'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UTCV')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UPH')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Economía'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'CHAPINGO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Administración'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'CHAPINGO')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Logística Naval'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'NAVAL')),
    ((SELECT id_carrera FROM carrera WHERE nombre_carrera = 'Gestión Empresarial'), (SELECT id_universidad FROM universidad WHERE nombre_universidad = 'UNPA'));

INSERT INTO curso_verano (nombre_curso_verano) VALUES
    ('Preescolar'),
    ('Primaria'),
    ('Secundaria'),
    ('Bachillerato'),
    ('Taller');

INSERT INTO materia (nombre_materia) VALUES
    ('Matemáticas'),
    ('Español'),
    ('Inglés'),
    ('Física'),
    ('Química');

INSERT INTO secundaria (nombre_secundaria) VALUES
    ('ESBAO'),
    ('GRAL 1'),
    ('GRAL 3'),
    ('ESTI 70'),
    ('ESTI 127'),
    ('TELESECUNDARIA');

INSERT INTO bachillerato (nombre_bachillerato) VALUES
    ('COVAEB 12'),
    ('CBTIS 47'),
    ('ESBAO'),
    ('COVAEB 46'),
    ('TEBAEV'),
    ('CETIS 143');
